name: Deploy

on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.Deploy.outputs.tag }}
    inputs:
      version:
        type: string
        required: true
      environment:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      version:
        description: 'Repo Tag Name (Ex.: 1.0.0-yyyymmdd-hhmmss)'
        type: string
        required: true
      environment:
        default: 'development'
        required: true
        type: choice
        options:
        - development
        - testing
        - staging
        - production

jobs:
  Deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      tag: ${{ inputs.version }}
    steps:
      - uses: actions/github-script@v6
        name: 'Check Git Tag'
        if: github.event_name == 'workflow_dispatch'
        with:
          script: |
            const refResponse = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ inputs.version }}'
            });
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_LAMBDA_REGION }}

      - name: 'Check S3 Bucket'
        if: github.event_name == 'workflow_dispatch'
        run: |
          aws s3api wait object-exists \
            --bucket ${{ secrets.AWS_S3_BUCKET_NAME }} \
            --key ${{ inputs.version }}.zip \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60

      - name: 'Update Source Code'
        id: update-lambda-function
        run: |
          echo "Environment: ${{ inputs.environment }}<br/>Version: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          aws lambda update-function-code \
            --function-name=${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --s3-bucket=${{ secrets.AWS_S3_BUCKET_NAME }} \
            --s3-key=${{ inputs.version }}.zip \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60
